phisoft/feecollec-web

CHANGELOG.md, README.md
- add title
- add overview
- add features
- add contact section
=> udpate README.md

index.html
=> [Update] header content #10

index.html, js/main.js
[Screen Recording - Made with FlexClip (1).webm](https://github.com/phisoft/feecollec-web/assets/156404474/cc58ccf2-27c1-41a3-918f-2f2a814317fe)
=> update navigation bar items #11

css/style.css, index.html, js/main.js
=> add FAQs section #13

css/style.css, index.html, js/main.js
=> Issue 19/update product overview in footer section

css/style.css, index.html, signup.html
The about section has been removed from feecollec.com website.
=> Issue 18/remove about section in web

index.html
=> add actions on updated navigation items #14

index.html
=> right align nav-bar #33

index.html
=> Issue 33/right align nav bar

index.html
=> change the subheading/title in service section #35

index.html, signup.html
=> link contact us to email hello@phisoft.my #22

index.html, signup.html
=> add quick action call to phone number in contact us #42

index.html, signup.html
=> Issue 43/add link google map for companys address footer

css/style.css, index.html
=> improve UX in FAQs section #36

css/style.css, index.html
=> Issue#49/change h1 to h3

index.html
=> Update contact form #52

index.html
=> Change input type num to text #56

css/style.css
I modify the CSS code and here is the loutput:
[Screen Recording - Made with FlexClip (1).webm](https://github.com/phisoft/feecollec-web/assets/156404474/d1b079b1-828b-4f41-ac98-2dcb1f9bb777)
=> Issue 55/test responsive website

index.html
=> update contact form using smtp #65

css/style.css, index.html
=> Issue 68/update faq list

css/style.css, index.html
=> Make it 2 columns on bigger screens #61

css/style.css, index.html
=> update faqs design #69

css/style.css, index.html
=> update solution info and add how it works #59 #60

index.html
=> Update footer feecollec description #74

index.html
=> fix spelling #76

index.html
=> Fix contact form fields #78

css/style.css, index.html
=> Issue 81/fix spelling feecollec

css/style.css, index.html
=> remove social media icons #80

index.html, robots.txt, sitemap.xml
- updated title to improve site crawlers - based on semrush tool's suggestion
- removed unused meta tags
=> update meta tags #57

css/style.css, index.html
=> Issue#92/change form layout

css/style.css, index.html
=> Issue #96/fix footer UI

index.html
=> Issue#95/change demo section text

css/style.css, index.html
=> fix ui how feecollec works #93

index.html
=> update description wording #101

css/style.css, index.html
https://github.com/phisoft/feecollec-web/assets/147354657/51d7a8e8-7fec-4715-bd29-5f02e3cafc0b
=> fix UI layout

css/style.css, index.html, js/main.js
https://github.com/phisoft/feecollec-web/assets/22228680/ff4a1769-0ba2-4b94-9de9-db5de5a41f22
=> Issue#109/update website theme

index.html
=> move picture above tagline in mobile view #130
